# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ./site
        strategy:
            matrix:
                node-version: [ 18.x ]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  # The version of Bun to install. (e.g. "latest", "canary", "0.5.6", <sha>)
                  bun-version: latest
            - name: Install dependencies
              run: bun install
              working-directory: ${{env.working-directory}}
            #    - name: Run tests
            #      run: npm test
            - name: Build
              run: bun run build
              working-directory: ${{env.working-directory}}
            - name: Deploy
              run: |
                  git config --global user.name $user_name
                  git config --global user.email $user_email
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  bun run deploy
              env:
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}